/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class CellView!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"


#include "OSGCell.h"
#include "OSGUIFont.h"

#include "OSGCellViewBase.h"
#include "OSGCellView.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::CellView
    A UI CellView
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<CellView *>::_type("CellViewPtr", "TableDomViewPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(CellView *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           CellView *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           CellView *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void CellViewBase::classDescInserter(TypeObject &oType)
{
}


CellViewBase::TypeObject CellViewBase::_type(
    CellViewBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&CellViewBase::createEmptyLocal),
    CellView::initMethod,
    CellView::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&CellView::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"CellView\"\n"
    "\tparent=\"TableDomView\"\n"
    "\tlibrary=\"ContribTableDom\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"true\"\n"
    "\tisNodeCore = \"false\"\n"
    "\tauthors = \"David Kabala (djkabala@gmail.com)\"\n"
    ">\n"
    "A UI CellView\n"
    "\t\n"
    "</FieldContainer>\n",
    "A UI CellView\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &CellViewBase::getType(void)
{
    return _type;
}

const FieldContainerType &CellViewBase::getType(void) const
{
    return _type;
}

UInt32 CellViewBase::getContainerSize(void) const
{
    return sizeof(CellView);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 CellViewBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void CellViewBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void CellViewBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
CellViewTransitPtr CellViewBase::createLocal(BitVector bFlags)
{
    CellViewTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<CellView>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
CellViewTransitPtr CellViewBase::createDependent(BitVector bFlags)
{
    CellViewTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<CellView>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
CellViewTransitPtr CellViewBase::create(void)
{
    CellViewTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<CellView>(tmpPtr);
    }

    return fc;
}

CellView *CellViewBase::createEmptyLocal(BitVector bFlags)
{
    CellView *returnValue;

    newPtr<CellView>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
CellView *CellViewBase::createEmpty(void)
{
    CellView *returnValue;

    newPtr<CellView>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr CellViewBase::shallowCopyLocal(
    BitVector bFlags) const
{
    CellView *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const CellView *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr CellViewBase::shallowCopyDependent(
    BitVector bFlags) const
{
    CellView *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const CellView *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr CellViewBase::shallowCopy(void) const
{
    CellView *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const CellView *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

CellViewBase::CellViewBase(void) :
    Inherited()
{
}

CellViewBase::CellViewBase(const CellViewBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

CellViewBase::~CellViewBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void CellViewBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    CellView *pThis = static_cast<CellView *>(this);

    pThis->execSync(static_cast<CellView *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *CellViewBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    CellView *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const CellView *>(pRefAspect),
                  dynamic_cast<const CellView *>(this));

    return returnValue;
}
#endif

void CellViewBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
