/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableDomArea
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEDOMAREABASE_H_
#define _OSGTABLEDOMAREABASE_H_
#ifdef __sgi
#pragma once
#endif


#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

//#include "OSGBaseTypes.h"

#include "OSGComponent.h" // Parent

#include "OSGTableDOM.h"          // TableDOMModel type
#include "OSGTableDomLayoutManager.h" // LayoutManager type
#include "OSGUIFontFields.h"            // Font type
#include "OSGSysFields.h"               // Editable type
#include "OSGBaseFields.h"              // BackgroundColor type

#include "OSGTableDomAreaFields.h"

OSG_BEGIN_NAMESPACE

class TableDomArea;

//! \brief TableDomArea Base Class.

class OSG_CONTRIBTABLEDOM_DLLMAPPING TableDomAreaBase : public Component
{
  public:

    typedef Component Inherited;
    typedef Component ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(TableDomArea);
    
    

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        TableDOMModelFieldId = Inherited::NextFieldId,
        LayoutManagerFieldId = TableDOMModelFieldId + 1,
        FontFieldId = LayoutManagerFieldId + 1,
        EditableFieldId = FontFieldId + 1,
        BackgroundColorFieldId = EditableFieldId + 1,
        NextFieldId = BackgroundColorFieldId + 1
    };

    static const OSG::BitVector TableDOMModelFieldMask =
        (TypeTraits<BitVector>::One << TableDOMModelFieldId);
    static const OSG::BitVector LayoutManagerFieldMask =
        (TypeTraits<BitVector>::One << LayoutManagerFieldId);
    static const OSG::BitVector FontFieldMask =
        (TypeTraits<BitVector>::One << FontFieldId);
    static const OSG::BitVector EditableFieldMask =
        (TypeTraits<BitVector>::One << EditableFieldId);
    static const OSG::BitVector BackgroundColorFieldMask =
        (TypeTraits<BitVector>::One << BackgroundColorFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFUnrecTableDOMPtr SFTableDOMModelType;
    typedef SFUnrecChildTableDomLayoutManagerPtr SFLayoutManagerType;
    typedef SFUnrecUIFontPtr  SFFontType;
    typedef SFBool            SFEditableType;
    typedef SFColor4f         SFBackgroundColorType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const SFUnrecTableDOMPtr  *getSFTableDOMModel  (void) const;
                  SFUnrecTableDOMPtr  *editSFTableDOMModel  (void);
            const SFUnrecChildTableDomLayoutManagerPtr *getSFLayoutManager  (void) const;
                  SFUnrecChildTableDomLayoutManagerPtr *editSFLayoutManager  (void);
            const SFUnrecUIFontPtr    *getSFFont           (void) const;
                  SFUnrecUIFontPtr    *editSFFont           (void);

                  SFBool              *editSFEditable       (void);
            const SFBool              *getSFEditable        (void) const;

                  SFColor4f           *editSFBackgroundColor(void);
            const SFColor4f           *getSFBackgroundColor (void) const;


                  TableDOM * getTableDOMModel  (void) const;

                  TableDomLayoutManager * getLayoutManager  (void) const;

                  UIFont * getFont           (void) const;

                  bool                &editEditable       (void);
                  bool                 getEditable        (void) const;

                  Color4f             &editBackgroundColor(void);
            const Color4f             &getBackgroundColor (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setTableDOMModel  (TableDOM * const value);
            void setLayoutManager  (TableDomLayoutManager * const value);
            void setFont           (UIFont * const value);
            void setEditable       (const bool value);
            void setBackgroundColor(const Color4f &value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  TableDomAreaTransitPtr  create          (void);
    static  TableDomArea           *createEmpty     (void);

    static  TableDomAreaTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  TableDomArea            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  TableDomAreaTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFUnrecTableDOMPtr _sfTableDOMModel;
    SFUnrecChildTableDomLayoutManagerPtr _sfLayoutManager;
    SFUnrecUIFontPtr  _sfFont;
    SFBool            _sfEditable;
    SFColor4f         _sfBackgroundColor;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    TableDomAreaBase(void);
    TableDomAreaBase(const TableDomAreaBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~TableDomAreaBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const TableDomArea *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name Child linking                                                */
    /*! \{                                                                 */

    virtual bool unlinkChild(FieldContainer * const pChild,
                             UInt16           const childFieldId);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleTableDOMModel   (void) const;
    EditFieldHandlePtr editHandleTableDOMModel  (void);
    GetFieldHandlePtr  getHandleLayoutManager   (void) const;
    EditFieldHandlePtr editHandleLayoutManager  (void);
    GetFieldHandlePtr  getHandleFont            (void) const;
    EditFieldHandlePtr editHandleFont           (void);
    GetFieldHandlePtr  getHandleEditable        (void) const;
    EditFieldHandlePtr editHandleEditable       (void);
    GetFieldHandlePtr  getHandleBackgroundColor (void) const;
    EditFieldHandlePtr editHandleBackgroundColor(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      TableDomAreaBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const TableDomAreaBase &source);
};

typedef TableDomAreaBase *TableDomAreaBaseP;

OSG_END_NAMESPACE

#endif /* _OSGTABLEDOMAREABASE_H_ */
