/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class TableDomVariableHeightLayoutManager!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"


#include "OSGCell.h"
#include "OSGTableDomLayoutManager.h"
#include "OSGCellView.h"
#include "OSGTableDomArea.h"
#include "OSGUIFont.h"


#include "OSGTableDomVariableHeightLayoutManagerBase.h"
#include "OSGTableDomVariableHeightLayoutManager.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::TableDomVariableHeightLayoutManager
    A TableDomVariableHeightLayoutManager
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<TableDomVariableHeightLayoutManager *>::_type("TableDomVariableHeightLayoutManagerPtr", "TableDomLayoutManagerPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(TableDomVariableHeightLayoutManager *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           TableDomVariableHeightLayoutManager *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           TableDomVariableHeightLayoutManager *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void TableDomVariableHeightLayoutManagerBase::classDescInserter(TypeObject &oType)
{
}


TableDomVariableHeightLayoutManagerBase::TypeObject TableDomVariableHeightLayoutManagerBase::_type(
    TableDomVariableHeightLayoutManagerBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&TableDomVariableHeightLayoutManagerBase::createEmptyLocal),
    TableDomVariableHeightLayoutManager::initMethod,
    TableDomVariableHeightLayoutManager::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&TableDomVariableHeightLayoutManager::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"TableDomVariableHeightLayoutManager\"\n"
    "\tparent=\"TableDomLayoutManager\"\n"
    "\tlibrary=\"ContribTableDom\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"true\"\n"
    "\tisNodeCore=\"false\"\n"
    "    authors=\"David Kabala\"\n"
    ">\n"
    "\n"
    "A TableDomVariableHeightLayoutManager\n"
    "\n"
    "\n"
    "</FieldContainer>\n",
    "A TableDomVariableHeightLayoutManager\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &TableDomVariableHeightLayoutManagerBase::getType(void)
{
    return _type;
}

const FieldContainerType &TableDomVariableHeightLayoutManagerBase::getType(void) const
{
    return _type;
}

UInt32 TableDomVariableHeightLayoutManagerBase::getContainerSize(void) const
{
    return sizeof(TableDomVariableHeightLayoutManager);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 TableDomVariableHeightLayoutManagerBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void TableDomVariableHeightLayoutManagerBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void TableDomVariableHeightLayoutManagerBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
TableDomVariableHeightLayoutManagerTransitPtr TableDomVariableHeightLayoutManagerBase::createLocal(BitVector bFlags)
{
    TableDomVariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<TableDomVariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
TableDomVariableHeightLayoutManagerTransitPtr TableDomVariableHeightLayoutManagerBase::createDependent(BitVector bFlags)
{
    TableDomVariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<TableDomVariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
TableDomVariableHeightLayoutManagerTransitPtr TableDomVariableHeightLayoutManagerBase::create(void)
{
    TableDomVariableHeightLayoutManagerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<TableDomVariableHeightLayoutManager>(tmpPtr);
    }

    return fc;
}

TableDomVariableHeightLayoutManager *TableDomVariableHeightLayoutManagerBase::createEmptyLocal(BitVector bFlags)
{
    TableDomVariableHeightLayoutManager *returnValue;

    newPtr<TableDomVariableHeightLayoutManager>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
TableDomVariableHeightLayoutManager *TableDomVariableHeightLayoutManagerBase::createEmpty(void)
{
    TableDomVariableHeightLayoutManager *returnValue;

    newPtr<TableDomVariableHeightLayoutManager>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr TableDomVariableHeightLayoutManagerBase::shallowCopyLocal(
    BitVector bFlags) const
{
    TableDomVariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableDomVariableHeightLayoutManager *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableDomVariableHeightLayoutManagerBase::shallowCopyDependent(
    BitVector bFlags) const
{
    TableDomVariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const TableDomVariableHeightLayoutManager *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr TableDomVariableHeightLayoutManagerBase::shallowCopy(void) const
{
    TableDomVariableHeightLayoutManager *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const TableDomVariableHeightLayoutManager *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

TableDomVariableHeightLayoutManagerBase::TableDomVariableHeightLayoutManagerBase(void) :
    Inherited()
{
}

TableDomVariableHeightLayoutManagerBase::TableDomVariableHeightLayoutManagerBase(const TableDomVariableHeightLayoutManagerBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

TableDomVariableHeightLayoutManagerBase::~TableDomVariableHeightLayoutManagerBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void TableDomVariableHeightLayoutManagerBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    TableDomVariableHeightLayoutManager *pThis = static_cast<TableDomVariableHeightLayoutManager *>(this);

    pThis->execSync(static_cast<TableDomVariableHeightLayoutManager *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *TableDomVariableHeightLayoutManagerBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    TableDomVariableHeightLayoutManager *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const TableDomVariableHeightLayoutManager *>(pRefAspect),
                  dynamic_cast<const TableDomVariableHeightLayoutManager *>(this));

    return returnValue;
}
#endif

void TableDomVariableHeightLayoutManagerBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
