/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEDOMVIEWFIELDS_H_
#define _OSGTABLEDOMVIEWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TableDomView;

OSG_GEN_CONTAINERPTR(TableDomView);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<TableDomView *> :
    public FieldTraitsFCPtrBase<TableDomView *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TableDomView *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTableDomViewPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTableDomViewPtr"; }
};

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableDomViewPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomView *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableDomViewPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomView *,
                      RecordedRefCountPolicy  > SFRecTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomView *,
                      UnrecordedRefCountPolicy> SFUnrecTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomView *,
                      WeakRefCountPolicy      > SFWeakTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomView *,
                      NoRefCountPolicy        > SFUncountedTableDomViewPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomView *,
                      RecordedRefCountPolicy  > MFRecTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomView *,
                      UnrecordedRefCountPolicy> MFUnrecTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomView *,
                      WeakRefCountPolicy      > MFWeakTableDomViewPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomView *,
                      NoRefCountPolicy        > MFUncountedTableDomViewPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecTableDomViewPtr : 
    public PointerSField<TableDomView *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecTableDomViewPtr : 
    public PointerSField<TableDomView *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakTableDomViewPtr :
    public PointerSField<TableDomView *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedTableDomViewPtr :
    public PointerSField<TableDomView *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecTableDomViewPtr :
    public PointerMField<TableDomView *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecTableDomViewPtr :
    public PointerMField<TableDomView *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakTableDomViewPtr :
    public PointerMField<TableDomView *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedTableDomViewPtr :
    public PointerMField<TableDomView *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEDOMVIEWFIELDS_H_ */
