/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEDOMVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_
#define _OSGTABLEDOMVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TableDomVariableHeightLayoutManager;

OSG_GEN_CONTAINERPTR(TableDomVariableHeightLayoutManager);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<TableDomVariableHeightLayoutManager *> :
    public FieldTraitsFCPtrBase<TableDomVariableHeightLayoutManager *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TableDomVariableHeightLayoutManager *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTableDomVariableHeightLayoutManagerPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTableDomVariableHeightLayoutManagerPtr"; }
};

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableDomVariableHeightLayoutManagerPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDomVariableHeightLayoutManager *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableDomVariableHeightLayoutManagerPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomVariableHeightLayoutManager *,
                      RecordedRefCountPolicy  > SFRecTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomVariableHeightLayoutManager *,
                      UnrecordedRefCountPolicy> SFUnrecTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomVariableHeightLayoutManager *,
                      WeakRefCountPolicy      > SFWeakTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDomVariableHeightLayoutManager *,
                      NoRefCountPolicy        > SFUncountedTableDomVariableHeightLayoutManagerPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomVariableHeightLayoutManager *,
                      RecordedRefCountPolicy  > MFRecTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomVariableHeightLayoutManager *,
                      UnrecordedRefCountPolicy> MFUnrecTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomVariableHeightLayoutManager *,
                      WeakRefCountPolicy      > MFWeakTableDomVariableHeightLayoutManagerPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDomVariableHeightLayoutManager *,
                      NoRefCountPolicy        > MFUncountedTableDomVariableHeightLayoutManagerPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecTableDomVariableHeightLayoutManagerPtr : 
    public PointerSField<TableDomVariableHeightLayoutManager *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecTableDomVariableHeightLayoutManagerPtr : 
    public PointerSField<TableDomVariableHeightLayoutManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakTableDomVariableHeightLayoutManagerPtr :
    public PointerSField<TableDomVariableHeightLayoutManager *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedTableDomVariableHeightLayoutManagerPtr :
    public PointerSField<TableDomVariableHeightLayoutManager *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecTableDomVariableHeightLayoutManagerPtr :
    public PointerMField<TableDomVariableHeightLayoutManager *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecTableDomVariableHeightLayoutManagerPtr :
    public PointerMField<TableDomVariableHeightLayoutManager *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakTableDomVariableHeightLayoutManagerPtr :
    public PointerMField<TableDomVariableHeightLayoutManager *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedTableDomVariableHeightLayoutManagerPtr :
    public PointerMField<TableDomVariableHeightLayoutManager *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEDOMVARIABLEHEIGHTLAYOUTMANAGERFIELDS_H_ */
