/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PlainTableDOM!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"


#include "OSGTableDOM.h"

#include "OSGPlainTableDOMBase.h"
#include "OSGPlainTableDOM.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PlainTableDOM
    UI PlainTableDOM.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<PlainTableDOM *>::_type("PlainTableDOMPtr", "AbstractTableDOMPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(PlainTableDOM *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PlainTableDOM *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PlainTableDOM *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PlainTableDOMBase::classDescInserter(TypeObject &oType)
{
}


PlainTableDOMBase::TypeObject PlainTableDOMBase::_type(
    PlainTableDOMBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&PlainTableDOMBase::createEmptyLocal),
    PlainTableDOM::initMethod,
    PlainTableDOM::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PlainTableDOM::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"PlainTableDOM\"\n"
    "\tparent=\"AbstractTableDOM\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "UI PlainTableDOM.\n"
    "</FieldContainer>\n",
    "UI PlainTableDOM.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PlainTableDOMBase::getType(void)
{
    return _type;
}

const FieldContainerType &PlainTableDOMBase::getType(void) const
{
    return _type;
}

UInt32 PlainTableDOMBase::getContainerSize(void) const
{
    return sizeof(PlainTableDOM);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 PlainTableDOMBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void PlainTableDOMBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void PlainTableDOMBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
PlainTableDOMTransitPtr PlainTableDOMBase::createLocal(BitVector bFlags)
{
    PlainTableDOMTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PlainTableDOM>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PlainTableDOMTransitPtr PlainTableDOMBase::createDependent(BitVector bFlags)
{
    PlainTableDOMTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PlainTableDOM>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PlainTableDOMTransitPtr PlainTableDOMBase::create(void)
{
    PlainTableDOMTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PlainTableDOM>(tmpPtr);
    }

    return fc;
}

PlainTableDOM *PlainTableDOMBase::createEmptyLocal(BitVector bFlags)
{
    PlainTableDOM *returnValue;

    newPtr<PlainTableDOM>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PlainTableDOM *PlainTableDOMBase::createEmpty(void)
{
    PlainTableDOM *returnValue;

    newPtr<PlainTableDOM>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

FieldContainerTransitPtr PlainTableDOMBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PlainTableDOM *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableDOM *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableDOMBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PlainTableDOM *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PlainTableDOM *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PlainTableDOMBase::shallowCopy(void) const
{
    PlainTableDOM *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PlainTableDOM *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

PlainTableDOMBase::PlainTableDOMBase(void) :
    Inherited()
{
}

PlainTableDOMBase::PlainTableDOMBase(const PlainTableDOMBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

PlainTableDOMBase::~PlainTableDOMBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void PlainTableDOMBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PlainTableDOM *pThis = static_cast<PlainTableDOM *>(this);

    pThis->execSync(static_cast<PlainTableDOM *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PlainTableDOMBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PlainTableDOM *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PlainTableDOM *>(pRefAspect),
                  dynamic_cast<const PlainTableDOM *>(this));

    return returnValue;
}
#endif

void PlainTableDOMBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
