/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPLAINTABLEDOMLEAFCELLFIELDS_H_
#define _OSGPLAINTABLEDOMLEAFCELLFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PlainTableDOMLeafCell;

OSG_GEN_CONTAINERPTR(PlainTableDOMLeafCell);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<PlainTableDOMLeafCell *> :
    public FieldTraitsFCPtrBase<PlainTableDOMLeafCell *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PlainTableDOMLeafCell *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPlainTableDOMLeafCellPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPlainTableDOMLeafCellPtr"; }
};

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPlainTableDOMLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMLeafCell *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPlainTableDOMLeafCellPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMLeafCell *,
                      RecordedRefCountPolicy  > SFRecPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMLeafCell *,
                      UnrecordedRefCountPolicy> SFUnrecPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMLeafCell *,
                      WeakRefCountPolicy      > SFWeakPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMLeafCell *,
                      NoRefCountPolicy        > SFUncountedPlainTableDOMLeafCellPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMLeafCell *,
                      RecordedRefCountPolicy  > MFRecPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMLeafCell *,
                      UnrecordedRefCountPolicy> MFUnrecPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMLeafCell *,
                      WeakRefCountPolicy      > MFWeakPlainTableDOMLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMLeafCell *,
                      NoRefCountPolicy        > MFUncountedPlainTableDOMLeafCellPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecPlainTableDOMLeafCellPtr : 
    public PointerSField<PlainTableDOMLeafCell *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecPlainTableDOMLeafCellPtr : 
    public PointerSField<PlainTableDOMLeafCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakPlainTableDOMLeafCellPtr :
    public PointerSField<PlainTableDOMLeafCell *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedPlainTableDOMLeafCellPtr :
    public PointerSField<PlainTableDOMLeafCell *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecPlainTableDOMLeafCellPtr :
    public PointerMField<PlainTableDOMLeafCell *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecPlainTableDOMLeafCellPtr :
    public PointerMField<PlainTableDOMLeafCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakPlainTableDOMLeafCellPtr :
    public PointerMField<PlainTableDOMLeafCell *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedPlainTableDOMLeafCellPtr :
    public PointerMField<PlainTableDOMLeafCell *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPLAINTABLEDOMLEAFCELLFIELDS_H_ */
