/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGPLAINTABLEDOMBRANCHCELLFIELDS_H_
#define _OSGPLAINTABLEDOMBRANCHCELLFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class PlainTableDOMBranchCell;

OSG_GEN_CONTAINERPTR(PlainTableDOMBranchCell);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<PlainTableDOMBranchCell *> :
    public FieldTraitsFCPtrBase<PlainTableDOMBranchCell *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PlainTableDOMBranchCell *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPlainTableDOMBranchCellPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPlainTableDOMBranchCellPtr"; }
};

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPlainTableDOMBranchCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<PlainTableDOMBranchCell *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPlainTableDOMBranchCellPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMBranchCell *,
                      RecordedRefCountPolicy  > SFRecPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMBranchCell *,
                      UnrecordedRefCountPolicy> SFUnrecPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMBranchCell *,
                      WeakRefCountPolicy      > SFWeakPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<PlainTableDOMBranchCell *,
                      NoRefCountPolicy        > SFUncountedPlainTableDOMBranchCellPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMBranchCell *,
                      RecordedRefCountPolicy  > MFRecPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMBranchCell *,
                      UnrecordedRefCountPolicy> MFUnrecPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMBranchCell *,
                      WeakRefCountPolicy      > MFWeakPlainTableDOMBranchCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<PlainTableDOMBranchCell *,
                      NoRefCountPolicy        > MFUncountedPlainTableDOMBranchCellPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecPlainTableDOMBranchCellPtr : 
    public PointerSField<PlainTableDOMBranchCell *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecPlainTableDOMBranchCellPtr : 
    public PointerSField<PlainTableDOMBranchCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakPlainTableDOMBranchCellPtr :
    public PointerSField<PlainTableDOMBranchCell *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedPlainTableDOMBranchCellPtr :
    public PointerSField<PlainTableDOMBranchCell *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecPlainTableDOMBranchCellPtr :
    public PointerMField<PlainTableDOMBranchCell *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecPlainTableDOMBranchCellPtr :
    public PointerMField<PlainTableDOMBranchCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakPlainTableDOMBranchCellPtr :
    public PointerMField<PlainTableDOMBranchCell *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedPlainTableDOMBranchCellPtr :
    public PointerMField<PlainTableDOMBranchCell *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGPLAINTABLEDOMBRANCHCELLFIELDS_H_ */
