/*---------------------------------------------------------------------------*\
 *                             VizTool                                 		 *
 *                                                                           *
 *               Copyright (C) 2010-2011 by Achyuthan Vasanth                *
 *                                                                           *
 *   authors:  Achyuthan Vasanth (achvas88@gmail.com)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PanelListComponentGenerator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OpenSG/OSGConfig.h"




#include "VTPanelListComponentGeneratorBase.h"
#include "VTPanelListComponentGenerator.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::PanelListComponentGenerator
    A PanelListComponentGenerator.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<PanelListComponentGenerator *>::_type("PanelListComponentGeneratorPtr", "DefaultListComponentGeneratorPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(PanelListComponentGenerator *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           PanelListComponentGenerator *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           PanelListComponentGenerator *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void PanelListComponentGeneratorBase::classDescInserter(TypeObject &oType)
{
}


PanelListComponentGeneratorBase::TypeObject PanelListComponentGeneratorBase::_type(
    PanelListComponentGeneratorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&PanelListComponentGeneratorBase::createEmptyLocal),
    PanelListComponentGenerator::initMethod,
    PanelListComponentGenerator::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&PanelListComponentGenerator::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"PanelListComponentGenerator\"\n"
    "\tparent=\"DefaultListComponentGenerator\"\n"
    "    library=\"VizTool\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "    systemcomponent=\"false\"\n"
    "    parentsystemcomponent=\"true\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"true\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"Achyuthan Vasanth (achvas88@gmail.com)                        \"\n"
    ">\n"
    "A PanelListComponentGenerator.\n"
    "\n"
    "</FieldContainer>\n",
    "A PanelListComponentGenerator.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &PanelListComponentGeneratorBase::getType(void)
{
    return _type;
}

const FieldContainerType &PanelListComponentGeneratorBase::getType(void) const
{
    return _type;
}

UInt32 PanelListComponentGeneratorBase::getContainerSize(void) const
{
    return sizeof(PanelListComponentGenerator);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 PanelListComponentGeneratorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void PanelListComponentGeneratorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void PanelListComponentGeneratorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
PanelListComponentGeneratorTransitPtr PanelListComponentGeneratorBase::createLocal(BitVector bFlags)
{
    PanelListComponentGeneratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<PanelListComponentGenerator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
PanelListComponentGeneratorTransitPtr PanelListComponentGeneratorBase::createDependent(BitVector bFlags)
{
    PanelListComponentGeneratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<PanelListComponentGenerator>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
PanelListComponentGeneratorTransitPtr PanelListComponentGeneratorBase::create(void)
{
    PanelListComponentGeneratorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<PanelListComponentGenerator>(tmpPtr);
    }

    return fc;
}

PanelListComponentGenerator *PanelListComponentGeneratorBase::createEmptyLocal(BitVector bFlags)
{
    PanelListComponentGenerator *returnValue;

    newPtr<PanelListComponentGenerator>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
PanelListComponentGenerator *PanelListComponentGeneratorBase::createEmpty(void)
{
    PanelListComponentGenerator *returnValue;

    newPtr<PanelListComponentGenerator>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr PanelListComponentGeneratorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    PanelListComponentGenerator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PanelListComponentGenerator *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr PanelListComponentGeneratorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    PanelListComponentGenerator *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const PanelListComponentGenerator *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr PanelListComponentGeneratorBase::shallowCopy(void) const
{
    PanelListComponentGenerator *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const PanelListComponentGenerator *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

PanelListComponentGeneratorBase::PanelListComponentGeneratorBase(void) :
    Inherited()
{
}

PanelListComponentGeneratorBase::PanelListComponentGeneratorBase(const PanelListComponentGeneratorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

PanelListComponentGeneratorBase::~PanelListComponentGeneratorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void PanelListComponentGeneratorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    PanelListComponentGenerator *pThis = static_cast<PanelListComponentGenerator *>(this);

    pThis->execSync(static_cast<PanelListComponentGenerator *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *PanelListComponentGeneratorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    PanelListComponentGenerator *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const PanelListComponentGenerator *>(pRefAspect),
                  dynamic_cast<const PanelListComponentGenerator *>(this));

    return returnValue;
}
#endif

void PanelListComponentGeneratorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
