/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTLEAFCELLFIELDS_H_
#define _OSGABSTRACTLEAFCELLFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class AbstractLeafCell;

OSG_GEN_CONTAINERPTR(AbstractLeafCell);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<AbstractLeafCell *> :
    public FieldTraitsFCPtrBase<AbstractLeafCell *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AbstractLeafCell *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAbstractLeafCellPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAbstractLeafCellPtr"; }
};

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractLeafCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractLeafCell *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractLeafCellPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractLeafCell *,
                      RecordedRefCountPolicy  > SFRecAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractLeafCell *,
                      UnrecordedRefCountPolicy> SFUnrecAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractLeafCell *,
                      WeakRefCountPolicy      > SFWeakAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractLeafCell *,
                      NoRefCountPolicy        > SFUncountedAbstractLeafCellPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractLeafCell *,
                      RecordedRefCountPolicy  > MFRecAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractLeafCell *,
                      UnrecordedRefCountPolicy> MFUnrecAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractLeafCell *,
                      WeakRefCountPolicy      > MFWeakAbstractLeafCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractLeafCell *,
                      NoRefCountPolicy        > MFUncountedAbstractLeafCellPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecAbstractLeafCellPtr : 
    public PointerSField<AbstractLeafCell *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecAbstractLeafCellPtr : 
    public PointerSField<AbstractLeafCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakAbstractLeafCellPtr :
    public PointerSField<AbstractLeafCell *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedAbstractLeafCellPtr :
    public PointerSField<AbstractLeafCell *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecAbstractLeafCellPtr :
    public PointerMField<AbstractLeafCell *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecAbstractLeafCellPtr :
    public PointerMField<AbstractLeafCell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakAbstractLeafCellPtr :
    public PointerMField<AbstractLeafCell *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedAbstractLeafCellPtr :
    public PointerMField<AbstractLeafCell *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTLEAFCELLFIELDS_H_ */
