/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class AbstractCell!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include "OSGConfig.h"



#include "OSGTableDOM.h"                // ParentTableDOM Class

#include "OSGAbstractCellBase.h"
#include "OSGAbstractCell.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::AbstractCell
    Table AbstractCell
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var TableDOM *      AbstractCellBase::_sfParentTableDOM
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<AbstractCell *>::_type("AbstractCellPtr", "CellPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(AbstractCell *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           AbstractCell *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           AbstractCell *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void AbstractCellBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecTableDOMPtr::Description(
        SFUnrecTableDOMPtr::getClassType(),
        "ParentTableDOM",
        "",
        ParentTableDOMFieldId, ParentTableDOMFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&AbstractCell::editHandleParentTableDOM),
        static_cast<FieldGetMethodSig >(&AbstractCell::getHandleParentTableDOM));

    oType.addInitialDesc(pDesc);
}


AbstractCellBase::TypeObject AbstractCellBase::_type(
    AbstractCellBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    NULL,
    AbstractCell::initMethod,
    AbstractCell::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&AbstractCell::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"AbstractCell\"\n"
    "\tparent=\"Cell\"\n"
    "    library=\"ContribTableDom\"\n"
    "    pointerfieldtypes=\"both\"\n"
    "\tstructure=\"abstract\"\n"
    "    systemcomponent=\"true\"\n"
    "    parentsystemcomponent=\"false\"\n"
    "    decoratable=\"false\"\n"
    "    useLocalIncludes=\"false\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "Table AbstractCell\n"
    "\t<Field\n"
    "\t\tname=\"ParentTableDOM\"\n"
    "\t\ttype=\"TableDOM\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tdefaultValue=\"NULL\"\n"
    "\t\taccess=\"protected\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "Table AbstractCell\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &AbstractCellBase::getType(void)
{
    return _type;
}

const FieldContainerType &AbstractCellBase::getType(void) const
{
    return _type;
}

UInt32 AbstractCellBase::getContainerSize(void) const
{
    return sizeof(AbstractCell);
}

/*------------------------- decorator get ------------------------------*/


//! Get the AbstractCell::_sfParentTableDOM field.
const SFUnrecTableDOMPtr *AbstractCellBase::getSFParentTableDOM(void) const
{
    return &_sfParentTableDOM;
}

SFUnrecTableDOMPtr  *AbstractCellBase::editSFParentTableDOM (void)
{
    editSField(ParentTableDOMFieldMask);

    return &_sfParentTableDOM;
}





/*------------------------------ access -----------------------------------*/

UInt32 AbstractCellBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (ParentTableDOMFieldMask & whichField))
    {
        returnValue += _sfParentTableDOM.getBinSize();
    }

    return returnValue;
}

void AbstractCellBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (ParentTableDOMFieldMask & whichField))
    {
        _sfParentTableDOM.copyToBin(pMem);
    }
}

void AbstractCellBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (ParentTableDOMFieldMask & whichField))
    {
        _sfParentTableDOM.copyFromBin(pMem);
    }
}



/*------------------------- constructors ----------------------------------*/

AbstractCellBase::AbstractCellBase(void) :
    Inherited(),
    _sfParentTableDOM         (NULL)
{
}

AbstractCellBase::AbstractCellBase(const AbstractCellBase &source) :
    Inherited(source),
    _sfParentTableDOM         (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

AbstractCellBase::~AbstractCellBase(void)
{
}

void AbstractCellBase::onCreate(const AbstractCell *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        AbstractCell *pThis = static_cast<AbstractCell *>(this);

        pThis->setParentTableDOM(source->getParentTableDOM());
    }
}

GetFieldHandlePtr AbstractCellBase::getHandleParentTableDOM  (void) const
{
    SFUnrecTableDOMPtr::GetHandlePtr returnValue(
        new  SFUnrecTableDOMPtr::GetHandle(
             &_sfParentTableDOM,
             this->getType().getFieldDesc(ParentTableDOMFieldId),
             const_cast<AbstractCellBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr AbstractCellBase::editHandleParentTableDOM (void)
{
    SFUnrecTableDOMPtr::EditHandlePtr returnValue(
        new  SFUnrecTableDOMPtr::EditHandle(
             &_sfParentTableDOM,
             this->getType().getFieldDesc(ParentTableDOMFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&AbstractCell::setParentTableDOM,
                    static_cast<AbstractCell *>(this), _1));

    editSField(ParentTableDOMFieldMask);

    return returnValue;
}



#ifdef OSG_MT_CPTR_ASPECT
void AbstractCellBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    AbstractCell *pThis = static_cast<AbstractCell *>(this);

    pThis->execSync(static_cast<AbstractCell *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif



void AbstractCellBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<AbstractCell *>(this)->setParentTableDOM(NULL);


}


OSG_END_NAMESPACE
