/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGABSTRACTTABLEDOMFIELDS_H_
#define _OSGABSTRACTTABLEDOMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class AbstractTableDOM;

OSG_GEN_CONTAINERPTR(AbstractTableDOM);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<AbstractTableDOM *> :
    public FieldTraitsFCPtrBase<AbstractTableDOM *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AbstractTableDOM *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAbstractTableDOMPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAbstractTableDOMPtr"; }
};

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAbstractTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<AbstractTableDOM *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAbstractTableDOMPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTableDOM *,
                      RecordedRefCountPolicy  > SFRecAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTableDOM *,
                      UnrecordedRefCountPolicy> SFUnrecAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTableDOM *,
                      WeakRefCountPolicy      > SFWeakAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<AbstractTableDOM *,
                      NoRefCountPolicy        > SFUncountedAbstractTableDOMPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTableDOM *,
                      RecordedRefCountPolicy  > MFRecAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTableDOM *,
                      UnrecordedRefCountPolicy> MFUnrecAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTableDOM *,
                      WeakRefCountPolicy      > MFWeakAbstractTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<AbstractTableDOM *,
                      NoRefCountPolicy        > MFUncountedAbstractTableDOMPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecAbstractTableDOMPtr : 
    public PointerSField<AbstractTableDOM *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecAbstractTableDOMPtr : 
    public PointerSField<AbstractTableDOM *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakAbstractTableDOMPtr :
    public PointerSField<AbstractTableDOM *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedAbstractTableDOMPtr :
    public PointerSField<AbstractTableDOM *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecAbstractTableDOMPtr :
    public PointerMField<AbstractTableDOM *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecAbstractTableDOMPtr :
    public PointerMField<AbstractTableDOM *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakAbstractTableDOMPtr :
    public PointerMField<AbstractTableDOM *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedAbstractTableDOMPtr :
    public PointerMField<AbstractTableDOM *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGABSTRACTTABLEDOMFIELDS_H_ */
