/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGCELLFIELDS_H_
#define _OSGCELLFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class Cell;

OSG_GEN_CONTAINERPTR(Cell);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<Cell *> :
    public FieldTraitsFCPtrBase<Cell *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Cell *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFCellPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFCellPtr"; }
};

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCellPtr"; 
}

template<> inline
const Char8 *FieldTraits<Cell *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCellPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<Cell *,
                      RecordedRefCountPolicy  > SFRecCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<Cell *,
                      UnrecordedRefCountPolicy> SFUnrecCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<Cell *,
                      WeakRefCountPolicy      > SFWeakCellPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<Cell *,
                      NoRefCountPolicy        > SFUncountedCellPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<Cell *,
                      RecordedRefCountPolicy  > MFRecCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<Cell *,
                      UnrecordedRefCountPolicy> MFUnrecCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<Cell *,
                      WeakRefCountPolicy      > MFWeakCellPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<Cell *,
                      NoRefCountPolicy        > MFUncountedCellPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecCellPtr : 
    public PointerSField<Cell *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecCellPtr : 
    public PointerSField<Cell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakCellPtr :
    public PointerSField<Cell *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedCellPtr :
    public PointerSField<Cell *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecCellPtr :
    public PointerMField<Cell *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecCellPtr :
    public PointerMField<Cell *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakCellPtr :
    public PointerMField<Cell *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedCellPtr :
    public PointerMField<Cell *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGCELLFIELDS_H_ */
