/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEDOMEVENTDETAILSFIELDS_H_
#define _OSGTABLEDOMEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TableDOMEventDetails;

OSG_GEN_CONTAINERPTR(TableDOMEventDetails);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<TableDOMEventDetails *> :
    public FieldTraitsFCPtrBase<TableDOMEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TableDOMEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTableDOMEventDetailsPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTableDOMEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableDOMEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOMEventDetails *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableDOMEventDetailsPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOMEventDetails *,
                      RecordedRefCountPolicy  > SFRecTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOMEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOMEventDetails *,
                      WeakRefCountPolicy      > SFWeakTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOMEventDetails *,
                      NoRefCountPolicy        > SFUncountedTableDOMEventDetailsPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOMEventDetails *,
                      RecordedRefCountPolicy  > MFRecTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOMEventDetails *,
                      UnrecordedRefCountPolicy> MFUnrecTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOMEventDetails *,
                      WeakRefCountPolicy      > MFWeakTableDOMEventDetailsPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOMEventDetails *,
                      NoRefCountPolicy        > MFUncountedTableDOMEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecTableDOMEventDetailsPtr : 
    public PointerSField<TableDOMEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecTableDOMEventDetailsPtr : 
    public PointerSField<TableDOMEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakTableDOMEventDetailsPtr :
    public PointerSField<TableDOMEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedTableDOMEventDetailsPtr :
    public PointerSField<TableDOMEventDetails *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecTableDOMEventDetailsPtr :
    public PointerMField<TableDOMEventDetails *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecTableDOMEventDetailsPtr :
    public PointerMField<TableDOMEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakTableDOMEventDetailsPtr :
    public PointerMField<TableDOMEventDetails *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedTableDOMEventDetailsPtr :
    public PointerMField<TableDOMEventDetails *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEDOMEVENTDETAILSFIELDS_H_ */
