/*---------------------------------------------------------------------------*\
 *                                OpenSG                                     *
 *                                                                           *
 *                                                                           *
 *               Copyright (C) 2000-2006 by the OpenSG Forum                 *
 *                                                                           *
 *                            www.opensg.org                                 *
 *                                                                           *
 *   contact:  David Kabala (djkabala@gmail.com)                             Achyuthan Vasanth (achvas88@gmail.com)*
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 2.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _OSGTABLEDOMFIELDS_H_
#define _OSGTABLEDOMFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include "OSGConfig.h"
#include "OSGContribTableDomDef.h"

#include "OSGFieldContainerFields.h"
#include "OSGPointerSField.h"
#include "OSGPointerMField.h"


OSG_BEGIN_NAMESPACE

class TableDOM;

OSG_GEN_CONTAINERPTR(TableDOM);

/*! \ingroup GrpContribTableDomFieldTraits
    \ingroup GrpLibOSGContribTableDom
 */
template <>
struct FieldTraits<TableDOM *> :
    public FieldTraitsFCPtrBase<TableDOM *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<TableDOM *>  Self;

    enum                        { Convertible = NotConvertible };

    static OSG_CONTRIBTABLEDOM_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFTableDOMPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFTableDOMPtr"; }
};

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakTableDOMPtr"; 
}

template<> inline
const Char8 *FieldTraits<TableDOM *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdTableDOMPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOM *,
                      RecordedRefCountPolicy  > SFRecTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOM *,
                      UnrecordedRefCountPolicy> SFUnrecTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOM *,
                      WeakRefCountPolicy      > SFWeakTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldSFields */
typedef PointerSField<TableDOM *,
                      NoRefCountPolicy        > SFUncountedTableDOMPtr;


/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOM *,
                      RecordedRefCountPolicy  > MFRecTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOM *,
                      UnrecordedRefCountPolicy> MFUnrecTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOM *,
                      WeakRefCountPolicy      > MFWeakTableDOMPtr;
/*! \ingroup GrpContribTableDomFieldMFields */
typedef PointerMField<TableDOM *,
                      NoRefCountPolicy        > MFUncountedTableDOMPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFRecTableDOMPtr : 
    public PointerSField<TableDOM *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUnrecTableDOMPtr : 
    public PointerSField<TableDOM *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFWeakTableDOMPtr :
    public PointerSField<TableDOM *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldSFields \ingroup GrpLibOSGContribTableDom */
struct SFUncountedTableDOMPtr :
    public PointerSField<TableDOM *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFRecTableDOMPtr :
    public PointerMField<TableDOM *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUnrecTableDOMPtr :
    public PointerMField<TableDOM *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFWeakTableDOMPtr :
    public PointerMField<TableDOM *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpContribTableDomFieldMFields \ingroup GrpLibOSGContribTableDom */
struct MFUncountedTableDOMPtr :
    public PointerMField<TableDOM *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _OSGTABLEDOMFIELDS_H_ */
